twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        'public/assets/css': styles
        'public/assets/adminlte/css/': adminlte
when@test:
    twig:
        strict_variables: true
