[build]
  command = "composer install && ./bin/console cache:clear && ./bin/console doctrine:migrations:migrate --no-interaction"
  publish = "public/"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
